# Generated by the protocol buffer compiler.  DO NOT EDIT!
# Source: chatdemo/chatdemo.proto for package 'chatdemo'

require 'grpc'
require 'chatdemo/chatdemo_pb'

module Chatdemo
  module ChatService
    class Service

      include ::GRPC::GenericService

      self.marshal_class_method = :encode
      self.unmarshal_class_method = :decode
      self.service_name = 'chatdemo.ChatService'

      rpc :SayHello, ::Chatdemo::HelloRequest, ::Chatdemo::HelloResponse
      rpc :SendMessage, stream(::Chatdemo::SendMessageRequest), stream(::Chatdemo::SendMessageResponse)
    end

    Stub = Service.rpc_stub_class
  end
end
