# frozen_string_literal: true
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: chatdemo/chatdemo.proto

require 'google/protobuf'


descriptor_data = "\n\x17\x63hatdemo/chatdemo.proto\x12\x08\x63hatdemo\"\"\n\x0cHelloRequest\x12\x12\n\x04name\x18\x01 \x01(\tR\x04name\")\n\rHelloResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\".\n\x12SendMessageRequest\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message\"/\n\x13SendMessageResponse\x12\x18\n\x07message\x18\x01 \x01(\tR\x07message2\x9a\x01\n\x0b\x43hatService\x12;\n\x08SayHello\x12\x16.chatdemo.HelloRequest\x1a\x17.chatdemo.HelloResponse\x12N\n\x0bSendMessage\x12\x1c.chatdemo.SendMessageRequest\x1a\x1d.chatdemo.SendMessageResponse(\x01\x30\x01\x42\x13Z\x11\x63hatdemo/chatdemob\x06proto3"

pool = Google::Protobuf::DescriptorPool.generated_pool
pool.add_serialized_file(descriptor_data)

module Chatdemo
  HelloRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chatdemo.HelloRequest").msgclass
  HelloResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chatdemo.HelloResponse").msgclass
  SendMessageRequest = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chatdemo.SendMessageRequest").msgclass
  SendMessageResponse = ::Google::Protobuf::DescriptorPool.generated_pool.lookup("chatdemo.SendMessageResponse").msgclass
end
