# chatgpt作なので単語のリストは適当です
words:
  あ: [あいす, あおば, あかね, あかり, あぎ]
  い: [いちご, いぬ, いす, いぶき, いげ]
  う: [うさぎ, うみ, うし, うた, うず]
  え: [えび, えんぴつ, えいご, えだまめ, えげ]
  お: [おかあさん, おおかみ, おかし, おねえさん, おご]
  か: [かさ, かぼちゃ, からす, かぜ, かぎ]
  が: [がけ, がく, がら, がしゃ, がん]
  き: [きつね, きりん, きんぎょ, きんたろう, きげ]
  ぎ: [ぎたあ, ぎん, ぎりぎり, ぎっくり, ぎす]
  く: [くじら, くま, くつ, くまさん, くず]
  ぐ: [ぐい, ぐらん, ぐりん, ぐる, ぐれ]
  け: [けんか, けもの, けんちく, けしき, けげ]
  こ: [こうもり, こあら, こうぼ, こいぬ, こず]
  ご: [ごちそう, ごくらく, ごろごろ, ごま, ごり]
  さ: [さくらんぼ, さかな, さけ, さつまいも, さぎ]
  ざ: [ざいりん, ざんぎり, ざらざら, ざん, ざぶ]
  し: [しまうま, しろくま, しお, しいたけ, しぐ]
  じ: [じいさん, じがらし, じこ, じごく, じす]
  す: [すいか, すな, すずめ, すず, すご]
  ず: [ずい, ずっと, ずれ, ずる, ずかん]
  せ: [せんす, せみ, せっけん, せんべい, せげ]
  ぜ: [ぜいたく, ぜんざい, ぜんまい, ぜつめん, ぜろ]
  そ: [そら, そらまめ, そば, そらがおか, そご]
  ぞ: [ぞう, ぞうり, ぞろぞろ, ぞんじる, ぞん]
  た: [たけ, たまご, たまねぎ, たんぽぽ, たず]
  だ: [だんじり, だし, だけ, だるま, だず]
  ち: [ちゅうりっぷ, ちち, ちょうちん, ちいさな, ちづ]
  ぢ: [ぢんし, ぢかん, ぢき, ぢり, ぢごく]
  つ: [つばめ, つぶ, つき, つまみ, つづ]
  づ: [づっき, づき, づみ, づぎり, づる]
  て: [てんじょう, てんとうむし, てんぷら, てれび, てづく]
  で: [でんしゃ, でんとう, でっぷり, でんでん, でき]
  と: [とり, とら, とりさん, とんぼ, とず]
  ど: [どろ, どげ, どじょう, どんぐり, どぐ]
  な: [なし, なす, なべ, なぞ, なづ]
  に: [にわとり, にんじん, にす, にょろにょろ, にず]
  ぬ: [ぬま, ぬいぐるみ, ぬの, ぬまえび, ぬづ]
  ね: [ねこ, ねずみ, ねぎ, ねんど, ねづ]
  の: [のっぽ, のり, のりもの, のっぺらぼう, のづ]
  は: [はし, はち, はな, はなび, はげ]
  ば: [ばす, ばん, ばら, ばれんたいん, ばげ]
  ぱ: [ぱすた, ぱん, ぱんつ, ぱらぱら, ぱげ]
  ひ: [ひまわり, ひつじ, ひかり, ひげ, ひず]
  び: [びしょう, びん, びわ, びたびた, びげ]
  ぴ: [ぴったり, ぴちょう, ぴろし, ぴく, ぴず]
  ふ: [ふうせん, ふくろう, ふね, ふたご, ふげ]
  ぶ: [ぶんか, ぶんしょう, ぶんせき, ぶた, ぶじ]
  ぷ: [ぷりん, ぷう, ぷりんと, ぷかぷか, ぷちぷち]
  へ: [へび, へそ, へいわ, へいし, へげ]
  べ: [べつ, べんとう, べんごし, べろべろ, べげ]
  ぺ: [ぺたんこ, ぺえじ, ぺちゃんこ, ぺろぺろ, ぺげ]
  ほ: [ほしぐも, ほたる, ほたて, ほたん, ほげ]
  ぼ: [ぼんさい, ぼんじり, ぼんち, ぼんやり, ぼげ]
  ぽ: [ぽかぽか, ぽぷりん, ぽてと, ぽん, ぽげ]
  ま: [まぐろ, まるい, まち, まめ, まげ]
  み: [みかん, みりん, みず, みすぼらしい, みげ]
  む: [むし, むぎ, むつごろう, むぎわら, むげ]
  め: [め, めんどうくさい, めん, めだか, めげ]
  も: [もち, もも, もちろん, もんじゃ, もげ]
  や: [やかん, やさい, やま, やきとり, やげ]
  ゆ: [ゆき, ゆび, ゆず, ゆうがた, ゆげ]
  よ: [よこぎり, よたか, よる, よもぎ, よげ]
  ら: [らいおん, らいす, らいがっぱ, らっきょう, らげ]
  り: [りんご, りん, りす, りくびき, りげ]
  る: [るす, るすぼん, るうれっと, るり, るげ]
  れ: [れいぞうこ, れんげ, れんが, れいぞうこ, れげ]
  ろ: [ろうか, ろうそく, ろくろ, ろうじん, ろげ]
  わ: [わに, わかめ, わけ, わら, わげ]
