// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: chatdemo/chatdemo.proto

package chatdemo

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ChatDemoServiceClient is the client API for ChatDemoService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ChatDemoServiceClient interface {
	// 動作確認用RPC
	SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error)
	// しりとりチャット用RPC
	WordChainChat(ctx context.Context, opts ...grpc.CallOption) (ChatDemoService_WordChainChatClient, error)
}

type chatDemoServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewChatDemoServiceClient(cc grpc.ClientConnInterface) ChatDemoServiceClient {
	return &chatDemoServiceClient{cc}
}

func (c *chatDemoServiceClient) SayHello(ctx context.Context, in *HelloRequest, opts ...grpc.CallOption) (*HelloResponse, error) {
	out := new(HelloResponse)
	err := c.cc.Invoke(ctx, "/chatdemo.ChatDemoService/SayHello", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *chatDemoServiceClient) WordChainChat(ctx context.Context, opts ...grpc.CallOption) (ChatDemoService_WordChainChatClient, error) {
	stream, err := c.cc.NewStream(ctx, &ChatDemoService_ServiceDesc.Streams[0], "/chatdemo.ChatDemoService/WordChainChat", opts...)
	if err != nil {
		return nil, err
	}
	x := &chatDemoServiceWordChainChatClient{stream}
	return x, nil
}

type ChatDemoService_WordChainChatClient interface {
	Send(*WordChain) error
	Recv() (*WordChain, error)
	grpc.ClientStream
}

type chatDemoServiceWordChainChatClient struct {
	grpc.ClientStream
}

func (x *chatDemoServiceWordChainChatClient) Send(m *WordChain) error {
	return x.ClientStream.SendMsg(m)
}

func (x *chatDemoServiceWordChainChatClient) Recv() (*WordChain, error) {
	m := new(WordChain)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatDemoServiceServer is the server API for ChatDemoService service.
// All implementations must embed UnimplementedChatDemoServiceServer
// for forward compatibility
type ChatDemoServiceServer interface {
	// 動作確認用RPC
	SayHello(context.Context, *HelloRequest) (*HelloResponse, error)
	// しりとりチャット用RPC
	WordChainChat(ChatDemoService_WordChainChatServer) error
	mustEmbedUnimplementedChatDemoServiceServer()
}

// UnimplementedChatDemoServiceServer must be embedded to have forward compatible implementations.
type UnimplementedChatDemoServiceServer struct {
}

func (UnimplementedChatDemoServiceServer) SayHello(context.Context, *HelloRequest) (*HelloResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SayHello not implemented")
}
func (UnimplementedChatDemoServiceServer) WordChainChat(ChatDemoService_WordChainChatServer) error {
	return status.Errorf(codes.Unimplemented, "method WordChainChat not implemented")
}
func (UnimplementedChatDemoServiceServer) mustEmbedUnimplementedChatDemoServiceServer() {}

// UnsafeChatDemoServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to ChatDemoServiceServer will
// result in compilation errors.
type UnsafeChatDemoServiceServer interface {
	mustEmbedUnimplementedChatDemoServiceServer()
}

func RegisterChatDemoServiceServer(s grpc.ServiceRegistrar, srv ChatDemoServiceServer) {
	s.RegisterService(&ChatDemoService_ServiceDesc, srv)
}

func _ChatDemoService_SayHello_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HelloRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(ChatDemoServiceServer).SayHello(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/chatdemo.ChatDemoService/SayHello",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(ChatDemoServiceServer).SayHello(ctx, req.(*HelloRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _ChatDemoService_WordChainChat_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(ChatDemoServiceServer).WordChainChat(&chatDemoServiceWordChainChatServer{stream})
}

type ChatDemoService_WordChainChatServer interface {
	Send(*WordChain) error
	Recv() (*WordChain, error)
	grpc.ServerStream
}

type chatDemoServiceWordChainChatServer struct {
	grpc.ServerStream
}

func (x *chatDemoServiceWordChainChatServer) Send(m *WordChain) error {
	return x.ServerStream.SendMsg(m)
}

func (x *chatDemoServiceWordChainChatServer) Recv() (*WordChain, error) {
	m := new(WordChain)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// ChatDemoService_ServiceDesc is the grpc.ServiceDesc for ChatDemoService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ChatDemoService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "chatdemo.ChatDemoService",
	HandlerType: (*ChatDemoServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SayHello",
			Handler:    _ChatDemoService_SayHello_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "WordChainChat",
			Handler:       _ChatDemoService_WordChainChat_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "chatdemo/chatdemo.proto",
}
