// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        (unknown)
// source: chatdemo/chatdemo.proto

package chatdemo

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Result int32

const (
	Result_RESULT_UNSPECIFIED Result = 0
	Result_RESULT_WIN         Result = 1
	Result_RESULT_LOSE        Result = 2
)

// Enum value maps for Result.
var (
	Result_name = map[int32]string{
		0: "RESULT_UNSPECIFIED",
		1: "RESULT_WIN",
		2: "RESULT_LOSE",
	}
	Result_value = map[string]int32{
		"RESULT_UNSPECIFIED": 0,
		"RESULT_WIN":         1,
		"RESULT_LOSE":        2,
	}
)

func (x Result) Enum() *Result {
	p := new(Result)
	*p = x
	return p
}

func (x Result) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Result) Descriptor() protoreflect.EnumDescriptor {
	return file_chatdemo_chatdemo_proto_enumTypes[0].Descriptor()
}

func (Result) Type() protoreflect.EnumType {
	return &file_chatdemo_chatdemo_proto_enumTypes[0]
}

func (x Result) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Result.Descriptor instead.
func (Result) EnumDescriptor() ([]byte, []int) {
	return file_chatdemo_chatdemo_proto_rawDescGZIP(), []int{0}
}

type HelloRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
}

func (x *HelloRequest) Reset() {
	*x = HelloRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatdemo_chatdemo_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloRequest) ProtoMessage() {}

func (x *HelloRequest) ProtoReflect() protoreflect.Message {
	mi := &file_chatdemo_chatdemo_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloRequest.ProtoReflect.Descriptor instead.
func (*HelloRequest) Descriptor() ([]byte, []int) {
	return file_chatdemo_chatdemo_proto_rawDescGZIP(), []int{0}
}

func (x *HelloRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type HelloResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Message string `protobuf:"bytes,1,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *HelloResponse) Reset() {
	*x = HelloResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatdemo_chatdemo_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *HelloResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HelloResponse) ProtoMessage() {}

func (x *HelloResponse) ProtoReflect() protoreflect.Message {
	mi := &file_chatdemo_chatdemo_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HelloResponse.ProtoReflect.Descriptor instead.
func (*HelloResponse) Descriptor() ([]byte, []int) {
	return file_chatdemo_chatdemo_proto_rawDescGZIP(), []int{1}
}

func (x *HelloResponse) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type WordChain struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Word    string `protobuf:"bytes,1,opt,name=word,proto3" json:"word,omitempty"`
	Result  Result `protobuf:"varint,2,opt,name=result,proto3,enum=chatdemo.Result" json:"result,omitempty"`
	Message string `protobuf:"bytes,3,opt,name=message,proto3" json:"message,omitempty"`
}

func (x *WordChain) Reset() {
	*x = WordChain{}
	if protoimpl.UnsafeEnabled {
		mi := &file_chatdemo_chatdemo_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *WordChain) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WordChain) ProtoMessage() {}

func (x *WordChain) ProtoReflect() protoreflect.Message {
	mi := &file_chatdemo_chatdemo_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WordChain.ProtoReflect.Descriptor instead.
func (*WordChain) Descriptor() ([]byte, []int) {
	return file_chatdemo_chatdemo_proto_rawDescGZIP(), []int{2}
}

func (x *WordChain) GetWord() string {
	if x != nil {
		return x.Word
	}
	return ""
}

func (x *WordChain) GetResult() Result {
	if x != nil {
		return x.Result
	}
	return Result_RESULT_UNSPECIFIED
}

func (x *WordChain) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_chatdemo_chatdemo_proto protoreflect.FileDescriptor

var file_chatdemo_chatdemo_proto_rawDesc = []byte{
	0x0a, 0x17, 0x63, 0x68, 0x61, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x64,
	0x65, 0x6d, 0x6f, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x08, 0x63, 0x68, 0x61, 0x74, 0x64,
	0x65, 0x6d, 0x6f, 0x22, 0x22, 0x0a, 0x0c, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75,
	0x65, 0x73, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x22, 0x29, 0x0a, 0x0d, 0x48, 0x65, 0x6c, 0x6c, 0x6f,
	0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6d, 0x65, 0x73, 0x73,
	0x61, 0x67, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x6d, 0x65, 0x73, 0x73, 0x61,
	0x67, 0x65, 0x22, 0x63, 0x0a, 0x09, 0x57, 0x6f, 0x72, 0x64, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x12,
	0x12, 0x0a, 0x04, 0x77, 0x6f, 0x72, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x77,
	0x6f, 0x72, 0x64, 0x12, 0x28, 0x0a, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x18, 0x02, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x10, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x52,
	0x65, 0x73, 0x75, 0x6c, 0x74, 0x52, 0x06, 0x72, 0x65, 0x73, 0x75, 0x6c, 0x74, 0x12, 0x18, 0x0a,
	0x07, 0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07,
	0x6d, 0x65, 0x73, 0x73, 0x61, 0x67, 0x65, 0x2a, 0x41, 0x0a, 0x06, 0x52, 0x65, 0x73, 0x75, 0x6c,
	0x74, 0x12, 0x16, 0x0a, 0x12, 0x52, 0x45, 0x53, 0x55, 0x4c, 0x54, 0x5f, 0x55, 0x4e, 0x53, 0x50,
	0x45, 0x43, 0x49, 0x46, 0x49, 0x45, 0x44, 0x10, 0x00, 0x12, 0x0e, 0x0a, 0x0a, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x5f, 0x57, 0x49, 0x4e, 0x10, 0x01, 0x12, 0x0f, 0x0a, 0x0b, 0x52, 0x45, 0x53,
	0x55, 0x4c, 0x54, 0x5f, 0x4c, 0x4f, 0x53, 0x45, 0x10, 0x02, 0x32, 0x8d, 0x01, 0x0a, 0x0f, 0x43,
	0x68, 0x61, 0x74, 0x44, 0x65, 0x6d, 0x6f, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3b,
	0x0a, 0x08, 0x53, 0x61, 0x79, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x12, 0x16, 0x2e, 0x63, 0x68, 0x61,
	0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x48, 0x65, 0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x71, 0x75, 0x65,
	0x73, 0x74, 0x1a, 0x17, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x48, 0x65,
	0x6c, 0x6c, 0x6f, 0x52, 0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x3d, 0x0a, 0x0d, 0x57,
	0x6f, 0x72, 0x64, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x43, 0x68, 0x61, 0x74, 0x12, 0x13, 0x2e, 0x63,
	0x68, 0x61, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x57, 0x6f, 0x72, 0x64, 0x43, 0x68, 0x61, 0x69,
	0x6e, 0x1a, 0x13, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2e, 0x57, 0x6f, 0x72,
	0x64, 0x43, 0x68, 0x61, 0x69, 0x6e, 0x28, 0x01, 0x30, 0x01, 0x42, 0x79, 0x0a, 0x0c, 0x63, 0x6f,
	0x6d, 0x2e, 0x63, 0x68, 0x61, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x42, 0x0d, 0x43, 0x68, 0x61, 0x74,
	0x64, 0x65, 0x6d, 0x6f, 0x50, 0x72, 0x6f, 0x74, 0x6f, 0x50, 0x01, 0x5a, 0x1a, 0x63, 0x68, 0x61,
	0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x63, 0x68, 0x61, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x2f, 0x63,
	0x68, 0x61, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0xa2, 0x02, 0x03, 0x43, 0x58, 0x58, 0xaa, 0x02, 0x08,
	0x43, 0x68, 0x61, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0xca, 0x02, 0x08, 0x43, 0x68, 0x61, 0x74, 0x64,
	0x65, 0x6d, 0x6f, 0xe2, 0x02, 0x14, 0x43, 0x68, 0x61, 0x74, 0x64, 0x65, 0x6d, 0x6f, 0x5c, 0x47,
	0x50, 0x42, 0x4d, 0x65, 0x74, 0x61, 0x64, 0x61, 0x74, 0x61, 0xea, 0x02, 0x08, 0x43, 0x68, 0x61,
	0x74, 0x64, 0x65, 0x6d, 0x6f, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_chatdemo_chatdemo_proto_rawDescOnce sync.Once
	file_chatdemo_chatdemo_proto_rawDescData = file_chatdemo_chatdemo_proto_rawDesc
)

func file_chatdemo_chatdemo_proto_rawDescGZIP() []byte {
	file_chatdemo_chatdemo_proto_rawDescOnce.Do(func() {
		file_chatdemo_chatdemo_proto_rawDescData = protoimpl.X.CompressGZIP(file_chatdemo_chatdemo_proto_rawDescData)
	})
	return file_chatdemo_chatdemo_proto_rawDescData
}

var file_chatdemo_chatdemo_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_chatdemo_chatdemo_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_chatdemo_chatdemo_proto_goTypes = []interface{}{
	(Result)(0),           // 0: chatdemo.Result
	(*HelloRequest)(nil),  // 1: chatdemo.HelloRequest
	(*HelloResponse)(nil), // 2: chatdemo.HelloResponse
	(*WordChain)(nil),     // 3: chatdemo.WordChain
}
var file_chatdemo_chatdemo_proto_depIdxs = []int32{
	0, // 0: chatdemo.WordChain.result:type_name -> chatdemo.Result
	1, // 1: chatdemo.ChatDemoService.SayHello:input_type -> chatdemo.HelloRequest
	3, // 2: chatdemo.ChatDemoService.WordChainChat:input_type -> chatdemo.WordChain
	2, // 3: chatdemo.ChatDemoService.SayHello:output_type -> chatdemo.HelloResponse
	3, // 4: chatdemo.ChatDemoService.WordChainChat:output_type -> chatdemo.WordChain
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_chatdemo_chatdemo_proto_init() }
func file_chatdemo_chatdemo_proto_init() {
	if File_chatdemo_chatdemo_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_chatdemo_chatdemo_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatdemo_chatdemo_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*HelloResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_chatdemo_chatdemo_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*WordChain); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_chatdemo_chatdemo_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_chatdemo_chatdemo_proto_goTypes,
		DependencyIndexes: file_chatdemo_chatdemo_proto_depIdxs,
		EnumInfos:         file_chatdemo_chatdemo_proto_enumTypes,
		MessageInfos:      file_chatdemo_chatdemo_proto_msgTypes,
	}.Build()
	File_chatdemo_chatdemo_proto = out.File
	file_chatdemo_chatdemo_proto_rawDesc = nil
	file_chatdemo_chatdemo_proto_goTypes = nil
	file_chatdemo_chatdemo_proto_depIdxs = nil
}
